// Auto-generated by: npx supabase gen types typescript --local > src/types/supabase.ts
// Re-run whenever you change the database schema.
// Manually updated for Sprint 23 migrations (20260701000003–20260701000005).
// Manually updated for Sprint 24 migrations (20260701000006–20260701000007).
// Manually updated for Sprint 25 migration  (20260701000009).
// Manually updated for Sprint 26 migration  (20260701000010).
// Manually updated for Sprint 28 migration  (20260701000011).
// Manually updated for Sprint 30 migration  (20260702000001):
//   events.canonical_discipline_slug, profiles passport columns,
//   challenges, challenge_titles, challenge_requirements,
//   completion_claims, athlete_challenge_progress, result_feeds.

export type Json =
  | string
  | number
  | boolean
  | null
  | { [key: string]: Json | undefined }
  | Json[]

export type Database = {
  public: {
    Tables: {
      disciplines: {
        Row: {
          id: string
          slug: string
          name: string
          short_description: string | null
          overview_content: string | null
          first_timer_guide: string | null
          faqs: Array<{ question: string; answer: string }>
          icon_name: string | null
          color: string
          related_discipline_slugs: string[]
          event_discipline_values: string[]
          order_index: number
          is_active: boolean
          created_at: string
          updated_at: string
        }
        Insert: {
          id?: string
          slug: string
          name: string
          short_description?: string | null
          overview_content?: string | null
          first_timer_guide?: string | null
          faqs?: Array<{ question: string; answer: string }>
          icon_name?: string | null
          color?: string
          related_discipline_slugs?: string[]
          event_discipline_values?: string[]
          order_index?: number
          is_active?: boolean
          created_at?: string
          updated_at?: string
        }
        Update: {
          id?: string
          slug?: string
          name?: string
          short_description?: string | null
          overview_content?: string | null
          first_timer_guide?: string | null
          faqs?: Array<{ question: string; answer: string }>
          icon_name?: string | null
          color?: string
          related_discipline_slugs?: string[]
          event_discipline_values?: string[]
          order_index?: number
          is_active?: boolean
          created_at?: string
          updated_at?: string
        }
        Relationships: []
      }
      series: {
        Row: {
          id: string
          slug: string
          name: string
          discipline_slug: string | null
          organiser: string | null
          short_description: string | null
          website_url: string | null
          country: string
          is_active: boolean
          created_at: string
          updated_at: string
        }
        Insert: {
          id?: string
          slug: string
          name: string
          discipline_slug?: string | null
          organiser?: string | null
          short_description?: string | null
          website_url?: string | null
          country?: string
          is_active?: boolean
          created_at?: string
          updated_at?: string
        }
        Update: {
          id?: string
          slug?: string
          name?: string
          discipline_slug?: string | null
          organiser?: string | null
          short_description?: string | null
          website_url?: string | null
          country?: string
          is_active?: boolean
          created_at?: string
          updated_at?: string
        }
        Relationships: [
          {
            foreignKeyName: 'series_discipline_slug_fkey'
            columns: ['discipline_slug']
            isOneToOne: false
            referencedRelation: 'disciplines'
            referencedColumns: ['slug']
          },
        ]
      }
      calendar_subscriptions: {
        Row: {
          id: string
          email: string
          categories: string[]
          source: string
          created_at: string
        }
        Insert: {
          id?: string
          email: string
          categories?: string[]
          source?: string
          created_at?: string
        }
        Update: {
          id?: string
          email?: string
          categories?: string[]
          source?: string
          created_at?: string
        }
        Relationships: []
      }
      profiles: {
        Row: {
          id: string
          username: string | null
          full_name: string | null
          first_name: string | null
          last_name: string | null
          date_of_birth: string | null
          gender: 'male' | 'female' | 'non_binary' | 'prefer_not_to_say' | null
          country: string | null
          state: string | null
          city: string | null
          preferred_sports: string[] | null
          profile_photo_url: string | null
          avatar_url: string | null
          role: 'user' | 'admin'
          // Sprint 30: Passport settings
          passport_is_public: boolean
          passport_bio: string | null
          passport_location: string | null
          show_finish_times: boolean
          show_active_challenges: boolean
          primary_title_id: string | null
          created_at: string
          updated_at: string
        }
        Insert: {
          id: string
          username?: string | null
          full_name?: string | null
          first_name?: string | null
          last_name?: string | null
          date_of_birth?: string | null
          gender?: 'male' | 'female' | 'non_binary' | 'prefer_not_to_say' | null
          country?: string | null
          state?: string | null
          city?: string | null
          preferred_sports?: string[] | null
          profile_photo_url?: string | null
          avatar_url?: string | null
          role?: 'user' | 'admin'
          passport_is_public?: boolean
          passport_bio?: string | null
          passport_location?: string | null
          show_finish_times?: boolean
          show_active_challenges?: boolean
          primary_title_id?: string | null
          created_at?: string
          updated_at?: string
        }
        Update: {
          id?: string
          username?: string | null
          full_name?: string | null
          first_name?: string | null
          last_name?: string | null
          date_of_birth?: string | null
          gender?: 'male' | 'female' | 'non_binary' | 'prefer_not_to_say' | null
          country?: string | null
          state?: string | null
          city?: string | null
          preferred_sports?: string[] | null
          profile_photo_url?: string | null
          avatar_url?: string | null
          role?: 'user' | 'admin'
          passport_is_public?: boolean
          passport_bio?: string | null
          passport_location?: string | null
          show_finish_times?: boolean
          show_active_challenges?: boolean
          primary_title_id?: string | null
          created_at?: string
          updated_at?: string
        }
        Relationships: []
      }
      tracks: {
        Row: {
          id: string
          name: string
          slug: string
          country: string
          region: string | null
          city: string | null
          length_km: number | null
          surface: string | null
          description: string | null
          image_url: string | null
          website_url: string | null
          latitude: number | null
          longitude: number | null
          is_published: boolean
          created_at: string
          updated_at: string
        }
        Insert: {
          id?: string
          name: string
          slug: string
          country: string
          region?: string | null
          city?: string | null
          length_km?: number | null
          surface?: string | null
          description?: string | null
          image_url?: string | null
          website_url?: string | null
          latitude?: number | null
          longitude?: number | null
          is_published?: boolean
          created_at?: string
          updated_at?: string
        }
        Update: {
          id?: string
          name?: string
          slug?: string
          country?: string
          region?: string | null
          city?: string | null
          length_km?: number | null
          surface?: string | null
          description?: string | null
          image_url?: string | null
          website_url?: string | null
          latitude?: number | null
          longitude?: number | null
          is_published?: boolean
          created_at?: string
          updated_at?: string
        }
        Relationships: []
      }
      championships: {
        Row: {
          id: string
          name: string
          slug: string
          discipline: string
          country: string | null
          season_year: number | null
          description: string | null
          image_url: string | null
          website_url: string | null
          organiser: string | null
          is_published: boolean
          created_at: string
          updated_at: string
        }
        Insert: {
          id?: string
          name: string
          slug: string
          discipline: string
          country?: string | null
          season_year?: number | null
          description?: string | null
          image_url?: string | null
          website_url?: string | null
          organiser?: string | null
          is_published?: boolean
          created_at?: string
          updated_at?: string
        }
        Update: {
          id?: string
          name?: string
          slug?: string
          discipline?: string
          country?: string | null
          season_year?: number | null
          description?: string | null
          image_url?: string | null
          website_url?: string | null
          organiser?: string | null
          is_published?: boolean
          created_at?: string
          updated_at?: string
        }
        Relationships: []
      }
      events: {
        Row: {
          id: string
          title: string
          slug: string
          event_type: string
          discipline: string
          track_id: string | null
          championship_id: string | null
          start_date: string
          end_date: string | null
          registration_deadline: string | null
          registration_opens_date: string | null
          registration_status: 'open' | 'closing_soon' | 'sold_out' | 'waitlist_only' | 'coming_soon' | 'ballot_open' | 'ballot_closed' | null
          early_bird_opens_date: string | null
          early_bird_closes_date: string | null
          early_bird_price_from: number | null
          early_bird_price_to: number | null
          late_entry_opens_date: string | null
          late_entry_price_from: number | null
          late_entry_price_to: number | null
          registration_url: string | null
          registration_platform: string | null
          waitlist_open: boolean
          waitlist_url: string | null
          waitlist_closes_date: string | null
          next_price_increase_date: string | null
          total_capacity: number | null
          refund_available: boolean | null
          refund_deadline: string | null
          transfer_available: boolean | null
          transfer_deadline: string | null
          deferral_available: boolean | null
          deferral_deadline: string | null
          policies_url: string | null
          qualification_required: boolean | null
          qualification_notes: string | null
          is_qualifier: boolean | null
          qualifier_for: string | null
          ballot_required: boolean | null
          ballot_opens_date: string | null
          ballot_closes_date: string | null
          ballot_results_date: string | null
          ballot_apply_url: string | null
          min_age: number | null
          max_age: number | null
          elevation_gain_m: number | null
          surface_type: 'road' | 'trail' | 'track' | 'mixed' | 'indoor' | 'water' | 'other' | null
          relay_available: boolean | null
          team_available: boolean | null
          wheelchair_available: boolean | null
          adaptive_available: boolean | null
          athlete_guide_url: string | null
          course_map_url: string | null
          gpx_file_url: string | null
          results_url: string | null
          first_year_held: number | null
          entry_fee_from: number | null
          entry_fee_to: number | null
          entry_fee_currency: string
          description: string | null
          format_notes: string | null
          whats_included: string[] | null
          difficulty: number | null
          image_url: string | null
          hero_image_url: string | null
          website_url: string | null
          organiser: string | null
          country: string
          region: string | null
          city: string | null
          venue_name: string | null
          venue_address: string | null
          latitude: number | null
          longitude: number | null
          transport_notes: string | null
          accommodation_notes: string | null
          series_slug: string | null
          data_verified_at: string | null
          data_confidence: number | null
          last_verified_date: string | null
          organiser_slug: string | null
          venue_slug: string | null
          event_status: 'confirmed' | 'postponed' | 'cancelled' | 'completed' | 'tbc'
          is_published: boolean
          is_featured: boolean
          created_at: string
          updated_at: string
          event_specific_overview: string | null
          public_transport_url: string | null
          parking_url: string | null
          spectator_info_url: string | null
          cbd_to_venue_public_transport_time: string | null
          cbd_to_venue_uber_time: string | null
          cbd_to_venue_uber_price_aud: string | null
          parking_notes: string | null
          spectator_notes: string | null
          travel_source_url: string | null
          travel_last_verified_date: string | null
          travel_data_confidence: number | null
          canonical_discipline_slug: string | null
          submission_source: string
          submitter_name: string | null
          submitter_email: string | null
        }
        Insert: {
          id?: string
          title: string
          slug: string
          event_type: string
          discipline: string
          track_id?: string | null
          championship_id?: string | null
          start_date: string
          end_date?: string | null
          registration_deadline?: string | null
          registration_opens_date?: string | null
          registration_status?: 'open' | 'closing_soon' | 'sold_out' | 'waitlist_only' | 'coming_soon' | 'ballot_open' | 'ballot_closed' | null
          early_bird_opens_date?: string | null
          early_bird_closes_date?: string | null
          early_bird_price_from?: number | null
          early_bird_price_to?: number | null
          late_entry_opens_date?: string | null
          late_entry_price_from?: number | null
          late_entry_price_to?: number | null
          registration_url?: string | null
          registration_platform?: string | null
          waitlist_open?: boolean
          waitlist_url?: string | null
          waitlist_closes_date?: string | null
          next_price_increase_date?: string | null
          total_capacity?: number | null
          refund_available?: boolean | null
          refund_deadline?: string | null
          transfer_available?: boolean | null
          transfer_deadline?: string | null
          deferral_available?: boolean | null
          deferral_deadline?: string | null
          policies_url?: string | null
          qualification_required?: boolean | null
          qualification_notes?: string | null
          is_qualifier?: boolean | null
          qualifier_for?: string | null
          ballot_required?: boolean | null
          ballot_opens_date?: string | null
          ballot_closes_date?: string | null
          ballot_results_date?: string | null
          ballot_apply_url?: string | null
          min_age?: number | null
          max_age?: number | null
          elevation_gain_m?: number | null
          surface_type?: 'road' | 'trail' | 'track' | 'mixed' | 'indoor' | 'water' | 'other' | null
          relay_available?: boolean | null
          team_available?: boolean | null
          wheelchair_available?: boolean | null
          adaptive_available?: boolean | null
          athlete_guide_url?: string | null
          course_map_url?: string | null
          gpx_file_url?: string | null
          results_url?: string | null
          first_year_held?: number | null
          entry_fee_from?: number | null
          entry_fee_to?: number | null
          entry_fee_currency?: string
          description?: string | null
          format_notes?: string | null
          whats_included?: string[] | null
          difficulty?: number | null
          image_url?: string | null
          hero_image_url?: string | null
          website_url?: string | null
          organiser?: string | null
          country: string
          region?: string | null
          city?: string | null
          venue_name?: string | null
          venue_address?: string | null
          latitude?: number | null
          longitude?: number | null
          transport_notes?: string | null
          accommodation_notes?: string | null
          series_slug?: string | null
          data_verified_at?: string | null
          data_confidence?: number | null
          last_verified_date?: string | null
          organiser_slug?: string | null
          venue_slug?: string | null
          event_status?: 'confirmed' | 'postponed' | 'cancelled' | 'completed' | 'tbc'
          is_published?: boolean
          is_featured?: boolean
          created_at?: string
          updated_at?: string
          event_specific_overview?: string | null
          public_transport_url?: string | null
          parking_url?: string | null
          spectator_info_url?: string | null
          cbd_to_venue_public_transport_time?: string | null
          cbd_to_venue_uber_time?: string | null
          cbd_to_venue_uber_price_aud?: string | null
          parking_notes?: string | null
          spectator_notes?: string | null
          travel_source_url?: string | null
          travel_last_verified_date?: string | null
          travel_data_confidence?: number | null
          canonical_discipline_slug?: string | null
          submission_source?: string
          submitter_name?: string | null
          submitter_email?: string | null
        }
        Update: {
          id?: string
          title?: string
          slug?: string
          event_type?: string
          discipline?: string
          track_id?: string | null
          championship_id?: string | null
          start_date?: string
          end_date?: string | null
          registration_deadline?: string | null
          registration_opens_date?: string | null
          registration_status?: 'open' | 'closing_soon' | 'sold_out' | 'waitlist_only' | 'coming_soon' | 'ballot_open' | 'ballot_closed' | null
          early_bird_opens_date?: string | null
          early_bird_closes_date?: string | null
          early_bird_price_from?: number | null
          early_bird_price_to?: number | null
          late_entry_opens_date?: string | null
          late_entry_price_from?: number | null
          late_entry_price_to?: number | null
          registration_url?: string | null
          registration_platform?: string | null
          waitlist_open?: boolean
          waitlist_url?: string | null
          waitlist_closes_date?: string | null
          next_price_increase_date?: string | null
          total_capacity?: number | null
          refund_available?: boolean | null
          refund_deadline?: string | null
          transfer_available?: boolean | null
          transfer_deadline?: string | null
          deferral_available?: boolean | null
          deferral_deadline?: string | null
          policies_url?: string | null
          qualification_required?: boolean | null
          qualification_notes?: string | null
          is_qualifier?: boolean | null
          qualifier_for?: string | null
          ballot_required?: boolean | null
          ballot_opens_date?: string | null
          ballot_closes_date?: string | null
          ballot_results_date?: string | null
          ballot_apply_url?: string | null
          min_age?: number | null
          max_age?: number | null
          elevation_gain_m?: number | null
          surface_type?: 'road' | 'trail' | 'track' | 'mixed' | 'indoor' | 'water' | 'other' | null
          relay_available?: boolean | null
          team_available?: boolean | null
          wheelchair_available?: boolean | null
          adaptive_available?: boolean | null
          athlete_guide_url?: string | null
          course_map_url?: string | null
          gpx_file_url?: string | null
          results_url?: string | null
          first_year_held?: number | null
          entry_fee_from?: number | null
          entry_fee_to?: number | null
          entry_fee_currency?: string
          description?: string | null
          format_notes?: string | null
          whats_included?: string[] | null
          difficulty?: number | null
          image_url?: string | null
          hero_image_url?: string | null
          website_url?: string | null
          organiser?: string | null
          country?: string
          region?: string | null
          city?: string | null
          venue_name?: string | null
          venue_address?: string | null
          latitude?: number | null
          longitude?: number | null
          transport_notes?: string | null
          accommodation_notes?: string | null
          series_slug?: string | null
          data_verified_at?: string | null
          data_confidence?: number | null
          last_verified_date?: string | null
          organiser_slug?: string | null
          venue_slug?: string | null
          event_status?: 'confirmed' | 'postponed' | 'cancelled' | 'completed' | 'tbc'
          is_published?: boolean
          is_featured?: boolean
          created_at?: string
          updated_at?: string
          event_specific_overview?: string | null
          public_transport_url?: string | null
          parking_url?: string | null
          spectator_info_url?: string | null
          cbd_to_venue_public_transport_time?: string | null
          cbd_to_venue_uber_time?: string | null
          cbd_to_venue_uber_price_aud?: string | null
          parking_notes?: string | null
          spectator_notes?: string | null
          travel_source_url?: string | null
          travel_last_verified_date?: string | null
          travel_data_confidence?: number | null
          canonical_discipline_slug?: string | null
          submission_source?: string
          submitter_name?: string | null
          submitter_email?: string | null
        }
        Relationships: [
          {
            foreignKeyName: 'events_track_id_fkey'
            columns: ['track_id']
            isOneToOne: false
            referencedRelation: 'tracks'
            referencedColumns: ['id']
          },
          {
            foreignKeyName: 'events_championship_id_fkey'
            columns: ['championship_id']
            isOneToOne: false
            referencedRelation: 'championships'
            referencedColumns: ['id']
          },
        ]
      }
      event_categories: {
        Row: {
          id: string
          event_id: string
          name: string
          distance_label: string | null
          entry_fee: number | null
          cutoff_minutes: number | null
          max_participants: number | null
          is_sold_out: boolean
          sort_order: number
          created_at: string
        }
        Insert: {
          id?: string
          event_id: string
          name: string
          distance_label?: string | null
          entry_fee?: number | null
          cutoff_minutes?: number | null
          max_participants?: number | null
          is_sold_out?: boolean
          sort_order?: number
          created_at?: string
        }
        Update: {
          id?: string
          event_id?: string
          name?: string
          distance_label?: string | null
          entry_fee?: number | null
          cutoff_minutes?: number | null
          max_participants?: number | null
          is_sold_out?: boolean
          sort_order?: number
          created_at?: string
        }
        Relationships: [
          {
            foreignKeyName: 'event_categories_event_id_fkey'
            columns: ['event_id']
            isOneToOne: false
            referencedRelation: 'events'
            referencedColumns: ['id']
          },
        ]
      }
      event_data_sources: {
        Row: {
          id: string
          event_id: string
          source_type: 'official_website' | 'organiser_email' | 'press_release' | 'manual' | 'automated'
          source_url: string | null
          last_checked_at: string | null
          last_changed_at: string | null
          check_interval_days: number
          confidence: number | null
          is_active: boolean
          notes: string | null
          created_at: string
          updated_at: string
        }
        Insert: {
          id?: string
          event_id: string
          source_type: 'official_website' | 'organiser_email' | 'press_release' | 'manual' | 'automated'
          source_url?: string | null
          last_checked_at?: string | null
          last_changed_at?: string | null
          check_interval_days?: number
          confidence?: number | null
          is_active?: boolean
          notes?: string | null
          created_at?: string
          updated_at?: string
        }
        Update: {
          id?: string
          event_id?: string
          source_type?: 'official_website' | 'organiser_email' | 'press_release' | 'manual' | 'automated'
          source_url?: string | null
          last_checked_at?: string | null
          last_changed_at?: string | null
          check_interval_days?: number
          confidence?: number | null
          is_active?: boolean
          notes?: string | null
          created_at?: string
          updated_at?: string
        }
        Relationships: [
          {
            foreignKeyName: 'event_data_sources_event_id_fkey'
            columns: ['event_id']
            isOneToOne: false
            referencedRelation: 'events'
            referencedColumns: ['id']
          },
        ]
      }
      event_relationships: {
        Row: {
          id: string
          event_id: string
          related_event_id: string
          relationship_type: 'same_series' | 'same_city' | 'same_organiser' | 'similar_discipline'
          sort_order: number
          created_at: string
        }
        Insert: {
          id?: string
          event_id: string
          related_event_id: string
          relationship_type: 'same_series' | 'same_city' | 'same_organiser' | 'similar_discipline'
          sort_order?: number
          created_at?: string
        }
        Update: {
          id?: string
          event_id?: string
          related_event_id?: string
          relationship_type?: 'same_series' | 'same_city' | 'same_organiser' | 'similar_discipline'
          sort_order?: number
          created_at?: string
        }
        Relationships: [
          {
            foreignKeyName: 'event_relationships_event_id_fkey'
            columns: ['event_id']
            isOneToOne: false
            referencedRelation: 'events'
            referencedColumns: ['id']
          },
          {
            foreignKeyName: 'event_relationships_related_event_id_fkey'
            columns: ['related_event_id']
            isOneToOne: false
            referencedRelation: 'events'
            referencedColumns: ['id']
          },
        ]
      }
      event_reminders: {
        Row: {
          id: string
          event_id: string
          user_id: string | null
          email: string | null
          reminder_type: 'registration_opens' | 'registration_closing' | 'early_bird_closing' | 'race_week'
          is_sent: boolean
          sent_at: string | null
          created_at: string
        }
        Insert: {
          id?: string
          event_id: string
          user_id?: string | null
          email?: string | null
          reminder_type: 'registration_opens' | 'registration_closing' | 'early_bird_closing' | 'race_week'
          is_sent?: boolean
          sent_at?: string | null
          created_at?: string
        }
        Update: {
          id?: string
          event_id?: string
          user_id?: string | null
          email?: string | null
          reminder_type?: 'registration_opens' | 'registration_closing' | 'race_week'
          is_sent?: boolean
          sent_at?: string | null
          created_at?: string
        }
        Relationships: [
          {
            foreignKeyName: 'event_reminders_event_id_fkey'
            columns: ['event_id']
            isOneToOne: false
            referencedRelation: 'events'
            referencedColumns: ['id']
          },
        ]
      }
      favourites: {
        Row: {
          id: string
          user_id: string
          entity_type: 'event' | 'track' | 'championship'
          entity_id: string
          created_at: string
        }
        Insert: {
          id?: string
          user_id: string
          entity_type: 'event' | 'track' | 'championship'
          entity_id: string
          created_at?: string
        }
        Update: {
          id?: string
          user_id?: string
          entity_type?: 'event' | 'track' | 'championship'
          entity_id?: string
          created_at?: string
        }
        Relationships: []
      }
      import_sources: {
        Row: {
          id: string
          name: string
          source_type: 'official_website' | 'national_body' | 'state_body' | 'trusted_aggregator' | 'organiser_direct'
          url: string | null
          organiser: string | null
          discipline: string | null
          country: string
          check_interval_days: number
          is_active: boolean
          last_checked_at: string | null
          notes: string | null
          created_at: string
          updated_at: string
        }
        Insert: {
          id?: string
          name: string
          source_type: 'official_website' | 'national_body' | 'state_body' | 'trusted_aggregator' | 'organiser_direct'
          url?: string | null
          organiser?: string | null
          discipline?: string | null
          country?: string
          check_interval_days?: number
          is_active?: boolean
          last_checked_at?: string | null
          notes?: string | null
          created_at?: string
          updated_at?: string
        }
        Update: {
          id?: string
          name?: string
          source_type?: 'official_website' | 'national_body' | 'state_body' | 'trusted_aggregator' | 'organiser_direct'
          url?: string | null
          organiser?: string | null
          discipline?: string | null
          country?: string
          check_interval_days?: number
          is_active?: boolean
          last_checked_at?: string | null
          notes?: string | null
          created_at?: string
          updated_at?: string
        }
        Relationships: []
      }
      import_batches: {
        Row: {
          id: string
          source_id: string | null
          import_type: 'manual' | 'scrape' | 'api' | 'csv'
          status: 'pending' | 'processing' | 'completed' | 'failed'
          total_records: number
          imported: number
          skipped: number
          errors: number
          imported_by: string | null
          notes: string | null
          started_at: string | null
          completed_at: string | null
          created_at: string
        }
        Insert: {
          id?: string
          source_id?: string | null
          import_type: 'manual' | 'scrape' | 'api' | 'csv'
          status?: 'pending' | 'processing' | 'completed' | 'failed'
          total_records?: number
          imported?: number
          skipped?: number
          errors?: number
          imported_by?: string | null
          notes?: string | null
          started_at?: string | null
          completed_at?: string | null
          created_at?: string
        }
        Update: {
          id?: string
          source_id?: string | null
          import_type?: 'manual' | 'scrape' | 'api' | 'csv'
          status?: 'pending' | 'processing' | 'completed' | 'failed'
          total_records?: number
          imported?: number
          skipped?: number
          errors?: number
          imported_by?: string | null
          notes?: string | null
          started_at?: string | null
          completed_at?: string | null
          created_at?: string
        }
        Relationships: [
          {
            foreignKeyName: 'import_batches_source_id_fkey'
            columns: ['source_id']
            isOneToOne: false
            referencedRelation: 'import_sources'
            referencedColumns: ['id']
          },
        ]
      }
      import_queue: {
        Row: {
          id: string
          batch_id: string | null
          matched_event_id: string | null
          action: 'create' | 'update' | 'skip'
          status: 'pending' | 'approved' | 'rejected' | 'applied'
          payload: Record<string, unknown>
          diff: Record<string, { old: unknown; new: unknown }> | null
          source_url: string | null
          confidence: number | null
          reviewer_id: string | null
          reviewed_at: string | null
          reviewer_notes: string | null
          created_at: string
          updated_at: string
        }
        Insert: {
          id?: string
          batch_id?: string | null
          matched_event_id?: string | null
          action: 'create' | 'update' | 'skip'
          status?: 'pending' | 'approved' | 'rejected' | 'applied'
          payload: Record<string, unknown>
          diff?: Record<string, { old: unknown; new: unknown }> | null
          source_url?: string | null
          confidence?: number | null
          reviewer_id?: string | null
          reviewed_at?: string | null
          reviewer_notes?: string | null
          created_at?: string
          updated_at?: string
        }
        Update: {
          id?: string
          batch_id?: string | null
          matched_event_id?: string | null
          action?: 'create' | 'update' | 'skip'
          status?: 'pending' | 'approved' | 'rejected' | 'applied'
          payload?: Record<string, unknown>
          diff?: Record<string, { old: unknown; new: unknown }> | null
          source_url?: string | null
          confidence?: number | null
          reviewer_id?: string | null
          reviewed_at?: string | null
          reviewer_notes?: string | null
          created_at?: string
          updated_at?: string
        }
        Relationships: [
          {
            foreignKeyName: 'import_queue_batch_id_fkey'
            columns: ['batch_id']
            isOneToOne: false
            referencedRelation: 'import_batches'
            referencedColumns: ['id']
          },
          {
            foreignKeyName: 'import_queue_matched_event_id_fkey'
            columns: ['matched_event_id']
            isOneToOne: false
            referencedRelation: 'events'
            referencedColumns: ['id']
          },
        ]
      }
      event_change_log: {
        Row: {
          id: string
          event_id: string
          changed_by: string | null
          change_source: 'admin_manual' | 'import_queue' | 'automated'
          import_queue_id: string | null
          field_name: string
          old_value: string | null
          new_value: string | null
          source_url: string | null
          confidence: number | null
          created_at: string
        }
        Insert: {
          id?: string
          event_id: string
          changed_by?: string | null
          change_source: 'admin_manual' | 'import_queue' | 'automated'
          import_queue_id?: string | null
          field_name: string
          old_value?: string | null
          new_value?: string | null
          source_url?: string | null
          confidence?: number | null
          created_at?: string
        }
        Update: {
          id?: string
          event_id?: string
          changed_by?: string | null
          change_source?: 'admin_manual' | 'import_queue' | 'automated'
          import_queue_id?: string | null
          field_name?: string
          old_value?: string | null
          new_value?: string | null
          source_url?: string | null
          confidence?: number | null
          created_at?: string
        }
        Relationships: [
          {
            foreignKeyName: 'event_change_log_event_id_fkey'
            columns: ['event_id']
            isOneToOne: false
            referencedRelation: 'events'
            referencedColumns: ['id']
          },
          {
            foreignKeyName: 'event_change_log_import_queue_id_fkey'
            columns: ['import_queue_id']
            isOneToOne: false
            referencedRelation: 'import_queue'
            referencedColumns: ['id']
          },
        ]
      }
      // ─── Sprint 30: Passport & Challenge System ───────────────────────────────
      challenges: {
        Row: {
          id: string
          slug: string
          name: string
          tagline: string | null
          description: string | null
          family: 'series' | 'pursuit' | 'collection'
          tier: 'starter' | 'achiever' | 'explorer' | 'legend'
          primary_discipline_slug: string | null
          geographic_scope: 'australia' | 'nz' | 'global' | null
          is_seasonal: boolean
          season_year: number | null
          is_retired: boolean
          retired_at: string | null
          events_required_total: number
          badge_image_url: string | null
          hero_image_url: string | null
          sort_order: number
          is_published: boolean
          created_at: string
          updated_at: string
        }
        Insert: {
          id?: string
          slug: string
          name: string
          tagline?: string | null
          description?: string | null
          family: 'series' | 'pursuit' | 'collection'
          tier: 'starter' | 'achiever' | 'explorer' | 'legend'
          primary_discipline_slug?: string | null
          geographic_scope?: 'australia' | 'nz' | 'global' | null
          is_seasonal?: boolean
          season_year?: number | null
          is_retired?: boolean
          retired_at?: string | null
          events_required_total?: number
          badge_image_url?: string | null
          hero_image_url?: string | null
          sort_order?: number
          is_published?: boolean
          created_at?: string
          updated_at?: string
        }
        Update: {
          id?: string
          slug?: string
          name?: string
          tagline?: string | null
          description?: string | null
          family?: 'series' | 'pursuit' | 'collection'
          tier?: 'starter' | 'achiever' | 'explorer' | 'legend'
          primary_discipline_slug?: string | null
          geographic_scope?: 'australia' | 'nz' | 'global' | null
          is_seasonal?: boolean
          season_year?: number | null
          is_retired?: boolean
          retired_at?: string | null
          events_required_total?: number
          badge_image_url?: string | null
          hero_image_url?: string | null
          sort_order?: number
          is_published?: boolean
          created_at?: string
          updated_at?: string
        }
        Relationships: [
          {
            foreignKeyName: 'challenges_primary_discipline_slug_fkey'
            columns: ['primary_discipline_slug']
            isOneToOne: false
            referencedRelation: 'disciplines'
            referencedColumns: ['slug']
          },
        ]
      }
      challenge_titles: {
        Row: {
          id: string
          challenge_id: string
          title: string
          description: string | null
        }
        Insert: {
          id?: string
          challenge_id: string
          title: string
          description?: string | null
        }
        Update: {
          id?: string
          challenge_id?: string
          title?: string
          description?: string | null
        }
        Relationships: [
          {
            foreignKeyName: 'challenge_titles_challenge_id_fkey'
            columns: ['challenge_id']
            isOneToOne: true
            referencedRelation: 'challenges'
            referencedColumns: ['id']
          },
        ]
      }
      challenge_requirements: {
        Row: {
          id: string
          challenge_id: string
          requirement_type: 'specific_event' | 'discipline' | 'geographic' | 'any_event'
          event_id: string | null
          discipline: string | null
          country: string | null
          region: string | null
          min_count: number
          display_label: string
          sort_order: number
        }
        Insert: {
          id?: string
          challenge_id: string
          requirement_type: 'specific_event' | 'discipline' | 'geographic' | 'any_event'
          event_id?: string | null
          discipline?: string | null
          country?: string | null
          region?: string | null
          min_count?: number
          display_label: string
          sort_order?: number
        }
        Update: {
          id?: string
          challenge_id?: string
          requirement_type?: 'specific_event' | 'discipline' | 'geographic' | 'any_event'
          event_id?: string | null
          discipline?: string | null
          country?: string | null
          region?: string | null
          min_count?: number
          display_label?: string
          sort_order?: number
        }
        Relationships: [
          {
            foreignKeyName: 'challenge_requirements_challenge_id_fkey'
            columns: ['challenge_id']
            isOneToOne: false
            referencedRelation: 'challenges'
            referencedColumns: ['id']
          },
          {
            foreignKeyName: 'challenge_requirements_event_id_fkey'
            columns: ['event_id']
            isOneToOne: false
            referencedRelation: 'events'
            referencedColumns: ['id']
          },
          {
            foreignKeyName: 'challenge_requirements_discipline_fkey'
            columns: ['discipline']
            isOneToOne: false
            referencedRelation: 'disciplines'
            referencedColumns: ['slug']
          },
        ]
      }
      completion_claims: {
        Row: {
          id: string
          athlete_id: string
          event_id: string
          event_date: string
          source: 'athlete_claim' | 'result_feed' | 'admin_import'
          status: 'pending' | 'under_review' | 'approved' | 'rejected' | 'appealing' | 'auto_approved'
          evidence_type: 'photo' | 'results_url' | 'bib_photo' | 'medal_photo' | null
          evidence_url: string | null
          evidence_notes: string | null
          finish_time: string | null
          bib_number: string | null
          official_position: number | null
          reviewed_by: string | null
          reviewed_at: string | null
          review_notes: string | null
          rejection_reason: 'insufficient_evidence' | 'evidence_mismatch' | 'duplicate' | 'event_not_in_database' | 'other' | null
          appeal_submitted_at: string | null
          appeal_notes: string | null
          result_feed_id: string | null
          created_at: string
          updated_at: string
        }
        Insert: {
          id?: string
          athlete_id: string
          event_id: string
          event_date: string
          source?: 'athlete_claim' | 'result_feed' | 'admin_import'
          status?: 'pending' | 'under_review' | 'approved' | 'rejected' | 'appealing' | 'auto_approved'
          evidence_type?: 'photo' | 'results_url' | 'bib_photo' | 'medal_photo' | null
          evidence_url?: string | null
          evidence_notes?: string | null
          finish_time?: string | null
          bib_number?: string | null
          official_position?: number | null
          reviewed_by?: string | null
          reviewed_at?: string | null
          review_notes?: string | null
          rejection_reason?: 'insufficient_evidence' | 'evidence_mismatch' | 'duplicate' | 'event_not_in_database' | 'other' | null
          appeal_submitted_at?: string | null
          appeal_notes?: string | null
          result_feed_id?: string | null
          created_at?: string
          updated_at?: string
        }
        Update: {
          id?: string
          athlete_id?: string
          event_id?: string
          event_date?: string
          source?: 'athlete_claim' | 'result_feed' | 'admin_import'
          status?: 'pending' | 'under_review' | 'approved' | 'rejected' | 'appealing' | 'auto_approved'
          evidence_type?: 'photo' | 'results_url' | 'bib_photo' | 'medal_photo' | null
          evidence_url?: string | null
          evidence_notes?: string | null
          finish_time?: string | null
          bib_number?: string | null
          official_position?: number | null
          reviewed_by?: string | null
          reviewed_at?: string | null
          review_notes?: string | null
          rejection_reason?: 'insufficient_evidence' | 'evidence_mismatch' | 'duplicate' | 'event_not_in_database' | 'other' | null
          appeal_submitted_at?: string | null
          appeal_notes?: string | null
          result_feed_id?: string | null
          created_at?: string
          updated_at?: string
        }
        Relationships: [
          {
            foreignKeyName: 'completion_claims_event_id_fkey'
            columns: ['event_id']
            isOneToOne: false
            referencedRelation: 'events'
            referencedColumns: ['id']
          },
        ]
      }
      athlete_challenge_progress: {
        Row: {
          id: string
          athlete_id: string
          challenge_id: string
          // [{requirement_id, display_label, needed, met, satisfied}]
          requirements_met: Json
          events_contributed: number
          events_required: number
          completion_pct: number
          is_complete: boolean
          completed_at: string | null
          earned_title_id: string | null
          last_computed_at: string
        }
        Insert: {
          id?: string
          athlete_id: string
          challenge_id: string
          requirements_met?: Json
          events_contributed?: number
          events_required?: number
          completion_pct?: number
          is_complete?: boolean
          completed_at?: string | null
          earned_title_id?: string | null
          last_computed_at?: string
        }
        Update: {
          id?: string
          athlete_id?: string
          challenge_id?: string
          requirements_met?: Json
          events_contributed?: number
          events_required?: number
          completion_pct?: number
          is_complete?: boolean
          completed_at?: string | null
          earned_title_id?: string | null
          last_computed_at?: string
        }
        Relationships: [
          {
            foreignKeyName: 'acp_challenge_id_fkey'
            columns: ['challenge_id']
            isOneToOne: false
            referencedRelation: 'challenges'
            referencedColumns: ['id']
          },
          {
            foreignKeyName: 'acp_earned_title_id_fkey'
            columns: ['earned_title_id']
            isOneToOne: false
            referencedRelation: 'challenge_titles'
            referencedColumns: ['id']
          },
        ]
      }
      result_feeds: {
        Row: {
          id: string
          event_id: string
          submitted_by_admin_id: string | null
          file_url: string | null
          status: 'pending_import' | 'processing' | 'imported' | 'failed'
          records_total: number | null
          records_matched: number | null
          records_auto_approved: number | null
          records_unmatched: number | null
          error_log: Json | null
          imported_at: string | null
          created_at: string
        }
        Insert: {
          id?: string
          event_id: string
          submitted_by_admin_id?: string | null
          file_url?: string | null
          status?: 'pending_import' | 'processing' | 'imported' | 'failed'
          records_total?: number | null
          records_matched?: number | null
          records_auto_approved?: number | null
          records_unmatched?: number | null
          error_log?: Json | null
          imported_at?: string | null
          created_at?: string
        }
        Update: {
          id?: string
          event_id?: string
          submitted_by_admin_id?: string | null
          file_url?: string | null
          status?: 'pending_import' | 'processing' | 'imported' | 'failed'
          records_total?: number | null
          records_matched?: number | null
          records_auto_approved?: number | null
          records_unmatched?: number | null
          error_log?: Json | null
          imported_at?: string | null
          created_at?: string
        }
        Relationships: [
          {
            foreignKeyName: 'result_feeds_event_id_fkey'
            columns: ['event_id']
            isOneToOne: false
            referencedRelation: 'events'
            referencedColumns: ['id']
          },
        ]
      }
    }
    Views: Record<string, never>
    Functions: {
      get_event_save_count: {
        Args: { p_event_id: string }
        Returns: number
      }
      compute_athlete_challenge_progress: {
        Args: { p_athlete_id: string; p_challenge_id: string }
        Returns: undefined
      }
    }
    Enums: Record<string, never>
    CompositeTypes: Record<string, never>
  }
}

export type Tables<T extends keyof Database['public']['Tables']> =
  Database['public']['Tables'][T]['Row']

export type TablesInsert<T extends keyof Database['public']['Tables']> =
  Database['public']['Tables'][T]['Insert']

export type TablesUpdate<T extends keyof Database['public']['Tables']> =
  Database['public']['Tables'][T]['Update']
