// Auto-generated by: npx supabase gen types typescript --local > src/types/supabase.ts
// Re-run whenever you change the database schema.

export type Json =
  | string
  | number
  | boolean
  | null
  | { [key: string]: Json | undefined }
  | Json[]

export type Database = {
  public: {
    Tables: {
      calendar_subscriptions: {
        Row: {
          id: string
          email: string
          categories: string[]
          source: string
          created_at: string
        }
        Insert: {
          id?: string
          email: string
          categories?: string[]
          source?: string
          created_at?: string
        }
        Update: {
          id?: string
          email?: string
          categories?: string[]
          source?: string
          created_at?: string
        }
        Relationships: []
      }
      profiles: {
        Row: {
          id: string
          username: string | null
          full_name: string | null
          first_name: string | null
          last_name: string | null
          date_of_birth: string | null
          gender: 'male' | 'female' | 'non_binary' | 'prefer_not_to_say' | null
          country: string | null
          state: string | null
          city: string | null
          preferred_sports: string[] | null
          profile_photo_url: string | null
          avatar_url: string | null
          role: 'user' | 'admin'
          created_at: string
          updated_at: string
        }
        Insert: {
          id: string
          username?: string | null
          full_name?: string | null
          first_name?: string | null
          last_name?: string | null
          date_of_birth?: string | null
          gender?: 'male' | 'female' | 'non_binary' | 'prefer_not_to_say' | null
          country?: string | null
          state?: string | null
          city?: string | null
          preferred_sports?: string[] | null
          profile_photo_url?: string | null
          avatar_url?: string | null
          role?: 'user' | 'admin'
          created_at?: string
          updated_at?: string
        }
        Update: {
          id?: string
          username?: string | null
          full_name?: string | null
          first_name?: string | null
          last_name?: string | null
          date_of_birth?: string | null
          gender?: 'male' | 'female' | 'non_binary' | 'prefer_not_to_say' | null
          country?: string | null
          state?: string | null
          city?: string | null
          preferred_sports?: string[] | null
          profile_photo_url?: string | null
          avatar_url?: string | null
          role?: 'user' | 'admin'
          created_at?: string
          updated_at?: string
        }
        Relationships: []
      }
      tracks: {
        Row: {
          id: string
          name: string
          slug: string
          country: string
          region: string | null
          city: string | null
          length_km: number | null
          surface: string | null
          description: string | null
          image_url: string | null
          website_url: string | null
          latitude: number | null
          longitude: number | null
          is_published: boolean
          created_at: string
          updated_at: string
        }
        Insert: {
          id?: string
          name: string
          slug: string
          country: string
          region?: string | null
          city?: string | null
          length_km?: number | null
          surface?: string | null
          description?: string | null
          image_url?: string | null
          website_url?: string | null
          latitude?: number | null
          longitude?: number | null
          is_published?: boolean
          created_at?: string
          updated_at?: string
        }
        Update: {
          id?: string
          name?: string
          slug?: string
          country?: string
          region?: string | null
          city?: string | null
          length_km?: number | null
          surface?: string | null
          description?: string | null
          image_url?: string | null
          website_url?: string | null
          latitude?: number | null
          longitude?: number | null
          is_published?: boolean
          created_at?: string
          updated_at?: string
        }
        Relationships: []
      }
      championships: {
        Row: {
          id: string
          name: string
          slug: string
          discipline: string
          country: string | null
          season_year: number | null
          description: string | null
          image_url: string | null
          website_url: string | null
          organiser: string | null
          is_published: boolean
          created_at: string
          updated_at: string
        }
        Insert: {
          id?: string
          name: string
          slug: string
          discipline: string
          country?: string | null
          season_year?: number | null
          description?: string | null
          image_url?: string | null
          website_url?: string | null
          organiser?: string | null
          is_published?: boolean
          created_at?: string
          updated_at?: string
        }
        Update: {
          id?: string
          name?: string
          slug?: string
          discipline?: string
          country?: string | null
          season_year?: number | null
          description?: string | null
          image_url?: string | null
          website_url?: string | null
          organiser?: string | null
          is_published?: boolean
          created_at?: string
          updated_at?: string
        }
        Relationships: []
      }
      events: {
        Row: {
          id: string
          title: string
          slug: string
          event_type: string
          discipline: string
          track_id: string | null
          championship_id: string | null
          start_date: string
          end_date: string | null
          registration_deadline: string | null
          description: string | null
          image_url: string | null
          website_url: string | null
          organiser: string | null
          country: string
          region: string | null
          city: string | null
          registration_status: 'open' | 'closing_soon' | 'sold_out' | 'coming_soon' | null
          is_published: boolean
          is_featured: boolean
          created_at: string
          updated_at: string
        }
        Insert: {
          id?: string
          title: string
          slug: string
          event_type: string
          discipline: string
          track_id?: string | null
          championship_id?: string | null
          start_date: string
          end_date?: string | null
          registration_deadline?: string | null
          registration_status?: 'open' | 'closing_soon' | 'sold_out' | 'coming_soon' | null
          description?: string | null
          image_url?: string | null
          website_url?: string | null
          organiser?: string | null
          country: string
          region?: string | null
          city?: string | null
          is_published?: boolean
          is_featured?: boolean
          created_at?: string
          updated_at?: string
        }
        Update: {
          id?: string
          title?: string
          slug?: string
          event_type?: string
          discipline?: string
          track_id?: string | null
          championship_id?: string | null
          start_date?: string
          end_date?: string | null
          registration_deadline?: string | null
          registration_status?: 'open' | 'closing_soon' | 'sold_out' | 'coming_soon' | null
          description?: string | null
          image_url?: string | null
          website_url?: string | null
          organiser?: string | null
          country?: string
          region?: string | null
          city?: string | null
          is_published?: boolean
          is_featured?: boolean
          created_at?: string
          updated_at?: string
        }
        Relationships: [
          {
            foreignKeyName: 'events_track_id_fkey'
            columns: ['track_id']
            isOneToOne: false
            referencedRelation: 'tracks'
            referencedColumns: ['id']
          },
          {
            foreignKeyName: 'events_championship_id_fkey'
            columns: ['championship_id']
            isOneToOne: false
            referencedRelation: 'championships'
            referencedColumns: ['id']
          },
        ]
      }
      favourites: {
        Row: {
          id: string
          user_id: string
          entity_type: 'event' | 'track' | 'championship'
          entity_id: string
          created_at: string
        }
        Insert: {
          id?: string
          user_id: string
          entity_type: 'event' | 'track' | 'championship'
          entity_id: string
          created_at?: string
        }
        Update: {
          id?: string
          user_id?: string
          entity_type?: 'event' | 'track' | 'championship'
          entity_id?: string
          created_at?: string
        }
        Relationships: []
      }
    }
    Views: Record<string, never>
    Functions: {
      get_event_save_count: {
        Args: { p_event_id: string }
        Returns: number
      }
    }
    Enums: Record<string, never>
    CompositeTypes: Record<string, never>
  }
}

export type Tables<T extends keyof Database['public']['Tables']> =
  Database['public']['Tables'][T]['Row']

export type TablesInsert<T extends keyof Database['public']['Tables']> =
  Database['public']['Tables'][T]['Insert']

export type TablesUpdate<T extends keyof Database['public']['Tables']> =
  Database['public']['Tables'][T]['Update']
