-- RaceRadar HQ — APAC Events seed
-- Generated from raceradarhq_apac_events_2026_27.csv
--
-- Column mapping:
--   event_name   → title
--   sport        → discipline
--   format       → event_type
--   registration_url → website_url
--   venue        → description
--   status=completed → is_published=false
--   status=upcoming/date_tbc → is_published=true
--   TBC dates    → '2099-01-01' placeholder (filter out on frontend with start_date < '2099-01-01')
--
-- Run this in: Supabase Dashboard → SQL Editor

INSERT INTO events (title, slug, discipline, event_type, city, country, start_date, end_date, website_url, description, is_published, is_featured)
VALUES

-- ── HYROX ─────────────────────────────────────────────────────────────────────
('BYD HYROX Sydney',
 'byd-hyrox-sydney',
 'HYROX', 'race', 'Sydney', 'Australia',
 '2026-07-01', '2026-07-05',
 'https://hyrox.com/event/hyrox-sydney/',
 'Venue: Sydney Showground Olympic Park',
 true, true),

('HYROX Brisbane (APAC Championship)',
 'hyrox-brisbane-apac-championship',
 'HYROX', 'race', 'Brisbane', 'Australia',
 '2026-04-09', '2026-04-12',
 'https://hyrox.com/event/hyrox-brisbane/',
 'Venue: Brisbane Convention & Exhibition Centre',
 false, false),

('AirAsia HYROX Perth',
 'airasia-hyrox-perth',
 'HYROX', 'race', 'Perth', 'Australia',
 '2026-08-21', '2026-08-23',
 'https://hyrox.com/event/hyrox-perth/',
 'Venue: Perth Convention & Exhibition Centre',
 true, true),

('HYROX Melbourne',
 'hyrox-melbourne',
 'HYROX', 'race', 'Melbourne', 'Australia',
 '2099-01-01', NULL,
 'https://hyrox.com/event/hyrox-melbourne/',
 'Venue: Melbourne Convention & Exhibition Centre',
 true, false),

('AirAsia HYROX Jakarta',
 'airasia-hyrox-jakarta',
 'HYROX', 'race', 'Jakarta', 'Indonesia',
 '2026-06-27', '2026-06-28',
 'https://hyrox.com/event/hyrox-jakarta/',
 NULL,
 false, false),

('AirAsia HYROX Chiba',
 'airasia-hyrox-chiba',
 'HYROX', 'race', 'Chiba', 'Japan',
 '2026-08-06', '2026-08-09',
 'https://hyrox.com/event/hyrox-chiba/',
 NULL,
 true, true),

('BYD HYROX Bangkok',
 'byd-hyrox-bangkok',
 'HYROX', 'race', 'Bangkok', 'Thailand',
 '2026-08-13', '2026-08-16',
 'https://hyrox.com/event/hyrox-bangkok-2/',
 NULL,
 true, false),

('AIA HYROX Singapore',
 'aia-hyrox-singapore',
 'HYROX', 'race', 'Singapore', 'Singapore',
 '2026-11-26', '2026-11-29',
 'https://hyrox.com/event/aia-hyrox-singapore/',
 NULL,
 true, true),

('AirAsia HYROX Seoul',
 'airasia-hyrox-seoul',
 'HYROX', 'race', 'Seoul', 'South Korea',
 '2026-11-14', '2026-11-15',
 'https://hyrox.com/event/hyrox-seoul/',
 NULL,
 true, false),

('TORRAS HYROX Hangzhou',
 'torras-hyrox-hangzhou',
 'HYROX', 'race', 'Hangzhou', 'China',
 '2026-07-04', '2026-07-05',
 'https://hyrox.com/event/hyrox-hangzhou/',
 NULL,
 true, false),

('TORRAS HYROX Shenzhen',
 'torras-hyrox-shenzhen',
 'HYROX', 'race', 'Shenzhen', 'China',
 '2026-08-15', '2026-08-16',
 'https://hyrox.com/event/hyrox-shenzhen/',
 NULL,
 true, false),

('HYROX Beijing',
 'hyrox-beijing',
 'HYROX', 'race', 'Beijing', 'China',
 '2026-09-12', '2026-09-13',
 'https://hyrox.com/event/hyrox-beijing-0912/',
 NULL,
 true, false),

('HYROX Shanghai',
 'hyrox-shanghai',
 'HYROX', 'race', 'Shanghai', 'China',
 '2026-10-31', '2026-11-01',
 'https://hyrox.com/event/hyrox-shanghai-1031/',
 NULL,
 true, false),

('HYROX Guangzhou',
 'hyrox-guangzhou',
 'HYROX', 'race', 'Guangzhou', 'China',
 '2026-11-21', '2026-11-22',
 'https://hyrox.com/event/hyrox-guangzhou/',
 NULL,
 true, false),

('HYROX Sanya',
 'hyrox-sanya',
 'HYROX', 'race', 'Sanya', 'China',
 '2026-12-05', '2026-12-06',
 'https://hyrox.com/event/30454/',
 NULL,
 true, false),

('HYROX World Championships 2027',
 'hyrox-world-championships-2027',
 'HYROX', 'race', 'Hong Kong', 'Hong Kong',
 '2099-01-01', NULL,
 'https://hyrox.com/hyrox-world-championships/',
 'Venue: AsiaWorld-Expo',
 true, true),

-- ── Spartan Race ──────────────────────────────────────────────────────────────
('2026 Central Coast Spartan Trifecta',
 '2026-central-coast-spartan-trifecta',
 'Spartan Race', 'race', 'Glenworth Valley', 'Australia',
 '2026-02-21', '2026-02-21',
 'https://au.spartan.com/en/races/centralcoast',
 'Venue: Glenworth Valley',
 false, false),

('2026 Spartan Race Ivory''s Rock Brisbane',
 '2026-spartan-race-ivorys-rock-brisbane',
 'Spartan Race', 'race', 'Ipswich', 'Australia',
 '2026-05-23', '2026-05-24',
 'https://au.spartan.com/en/races/ivorysrock2026',
 'Venue: Ivory''s Rock',
 false, false),

('2026 Melbourne Spartan Event Weekend',
 '2026-melbourne-spartan-event-weekend',
 'Spartan Race', 'race', 'Melbourne', 'Australia',
 '2026-08-08', '2026-08-09',
 'https://au.spartan.com/en/races/melbourne2026',
 'Venue: Werribee Racecourse',
 true, true),

('2026 Wollongong Spartan Stadion',
 '2026-wollongong-spartan-stadion',
 'Spartan Race', 'race', 'Wollongong', 'Australia',
 '2026-10-10', '2026-10-10',
 'https://au.spartan.com/en/race/find-race',
 NULL,
 true, false),

('2026 Lakes Entrance Spartan Ultra Trifecta',
 '2026-lakes-entrance-spartan-ultra-trifecta',
 'Spartan Race', 'race', 'Lakes Entrance', 'Australia',
 '2026-11-21', '2026-11-22',
 'https://au.spartan.com/en/races/lakes-entrance',
 NULL,
 true, false),

('Spartan Race Mt Fuji Susono Japan',
 'spartan-race-mt-fuji-susono-japan',
 'Spartan Race', 'race', 'Susono', 'Japan',
 '2026-07-25', '2026-07-25',
 'https://jp.spartan.com/en/race/find-race',
 'Venue: Mt Fuji Susono',
 true, false),

('Spartan APAC Championship Chongli',
 'spartan-apac-championship-chongli',
 'Spartan Race', 'race', 'Chongli', 'China',
 '2026-08-15', '2026-08-16',
 'https://www.spartan.com/en/race/detail/10133/overview',
 'Venue: Genting Snow Park',
 true, true),

('Spartan Race Thailand Bangkok',
 'spartan-race-thailand-bangkok',
 'Spartan Race', 'race', 'Bangkok', 'Thailand',
 '2099-01-01', NULL,
 'https://th.spartan.com',
 NULL,
 true, false),

-- ── Ironman ───────────────────────────────────────────────────────────────────
('IRONMAN New Zealand Taupo',
 'ironman-new-zealand-taupo',
 'Ironman', 'race', 'Taupo', 'New Zealand',
 '2026-03-07', '2026-03-07',
 'https://www.ironman.com/im-new-zealand',
 'Venue: Lake Taupo',
 false, false),

('IRONMAN 70.3 Taupo',
 'ironman-703-taupo',
 'Ironman 70.3', 'race', 'Taupo', 'New Zealand',
 '2026-03-07', '2026-03-07',
 'https://www.ironman.com/im703-taupo',
 'Venue: Lake Taupo',
 false, false),

('IRONMAN 70.3 Geelong',
 'ironman-703-geelong',
 'Ironman 70.3', 'race', 'Geelong', 'Australia',
 '2026-03-22', '2026-03-22',
 'https://www.ironman.com/im703-geelong',
 'Venue: Eastern Beach',
 false, false),

('IRONMAN 70.3 Western Sydney',
 'ironman-703-western-sydney',
 'Ironman 70.3', 'race', 'Western Sydney', 'Australia',
 '2026-05-03', '2026-05-03',
 'https://www.ironman.com/im703-western-sydney',
 'Venue: Sydney International Regatta Centre',
 false, false),

('IRONMAN Cairns',
 'ironman-cairns',
 'Ironman', 'race', 'Cairns', 'Australia',
 '2026-06-14', '2026-06-14',
 'https://www.ironman.com/im-cairns',
 NULL,
 false, false),

('IRONMAN 70.3 Cairns',
 'ironman-703-cairns',
 'Ironman 70.3', 'race', 'Cairns', 'Australia',
 '2026-06-14', '2026-06-14',
 'https://www.ironman.com/im703-cairns',
 NULL,
 false, false),

('IRONMAN 70.3 Sunshine Coast',
 'ironman-703-sunshine-coast',
 'Ironman 70.3', 'race', 'Mooloolaba', 'Australia',
 '2026-09-13', '2026-09-13',
 'https://www.ironman.com/im703-sunshine-coast',
 NULL,
 true, true),

('IRONMAN Australia Port Macquarie',
 'ironman-australia-port-macquarie',
 'Ironman', 'race', 'Port Macquarie', 'Australia',
 '2026-10-18', '2026-10-18',
 'https://www.ironman.com/im-australia',
 NULL,
 true, true),

('IRONMAN 70.3 Port Macquarie',
 'ironman-703-port-macquarie',
 'Ironman 70.3', 'race', 'Port Macquarie', 'Australia',
 '2026-10-18', '2026-10-18',
 'https://www.ironman.com/im703-port-macquarie',
 NULL,
 true, false),

('IRONMAN 70.3 St Kilda Melbourne',
 'ironman-703-st-kilda-melbourne',
 'Ironman 70.3', 'race', 'Melbourne', 'Australia',
 '2026-11-08', '2026-11-08',
 'https://www.ironman.com/im703-melbourne',
 NULL,
 true, false),

('IRONMAN Western Australia Busselton',
 'ironman-western-australia-busselton',
 'Ironman', 'race', 'Busselton', 'Australia',
 '2026-12-06', '2026-12-06',
 'https://www.ironman.com/im-western-australia',
 NULL,
 true, false),

('IRONMAN 70.3 Busselton',
 'ironman-703-busselton',
 'Ironman 70.3', 'race', 'Busselton', 'Australia',
 '2026-12-06', '2026-12-06',
 'https://www.ironman.com/im703-busselton',
 NULL,
 true, false),

('IRONMAN 70.3 Lapu Lapu Philippines',
 'ironman-703-lapu-lapu-philippines',
 'Ironman 70.3', 'race', 'Lapu-Lapu City', 'Philippines',
 '2099-01-01', NULL,
 'https://www.ironman.com/im703-lapu-lapu',
 'Venue: Cebu Philippines',
 true, false),

('IRONMAN Vietnam Da Nang',
 'ironman-vietnam-da-nang',
 'Ironman', 'race', 'Da Nang', 'Vietnam',
 '2099-01-01', NULL,
 'https://www.ironman.com/im-vietnam',
 NULL,
 true, false),

-- ── Marathon ──────────────────────────────────────────────────────────────────
('TCS Sydney Marathon',
 'tcs-sydney-marathon',
 'Marathon', 'race', 'Sydney', 'Australia',
 '2026-08-30', '2026-08-30',
 'https://sydneymarathon.com',
 'Venue: Sydney Harbour Bridge to Opera House',
 true, true),

('ASICS Gold Coast Marathon',
 'asics-gold-coast-marathon',
 'Marathon', 'race', 'Gold Coast', 'Australia',
 '2026-07-05', '2026-07-05',
 'https://goldcoastmarathon.com.au',
 'Venue: Broadwater Parklands',
 true, false),

('ASICS Gold Coast Half Marathon',
 'asics-gold-coast-half-marathon',
 'Marathon', 'race', 'Gold Coast', 'Australia',
 '2026-07-04', '2026-07-04',
 'https://goldcoastmarathon.com.au/enter/',
 'Venue: Broadwater Parklands',
 true, false),

('Nike Melbourne Marathon Festival',
 'nike-melbourne-marathon-festival',
 'Marathon', 'race', 'Melbourne', 'Australia',
 '2026-10-11', '2026-10-11',
 'https://melbournemarathon.com.au',
 'Venue: Batman Avenue to MCG',
 true, true),

('Seoul Marathon 96th Dong-A',
 'seoul-marathon-96th-dong-a',
 'Marathon', 'race', 'Seoul', 'South Korea',
 '2026-03-15', '2026-03-15',
 'https://en.seoul-marathon.com',
 'Venue: Gwanghwamun Square',
 false, false),

('Tokyo Marathon 2027',
 'tokyo-marathon-2027',
 'Marathon', 'race', 'Tokyo', 'Japan',
 '2027-03-07', '2027-03-07',
 'https://www.marathon.tokyo/en',
 'Venue: Shinjuku to Tokyo Big Sight',
 true, false),

('Standard Chartered Singapore Marathon',
 'standard-chartered-singapore-marathon',
 'Marathon', 'race', 'Singapore', 'Singapore',
 '2026-12-06', '2026-12-06',
 'https://singaporemarathon.com',
 'Venue: Marina Bay',
 true, false),

-- ── Trail Running ─────────────────────────────────────────────────────────────
('HOKA Ultra-Trail Australia by UTMB',
 'hoka-ultra-trail-australia-utmb',
 'Trail Running', 'race', 'Katoomba', 'Australia',
 '2026-05-14', '2026-05-17',
 'https://uta.utmb.world',
 'Venue: Scenic World Katoomba, Blue Mountains',
 false, false),

('TransLantau by UTMB',
 'translantau-by-utmb',
 'Trail Running', 'race', 'Lantau Island', 'Hong Kong',
 '2026-11-13', '2026-11-15',
 'https://utmb.world',
 NULL,
 true, false),

('HOKA Chiang Mai Thailand by UTMB',
 'hoka-chiang-mai-thailand-utmb',
 'Trail Running', 'race', 'Chiang Mai', 'Thailand',
 '2099-01-01', NULL,
 'https://utmb.world/utmb-world-series-events',
 NULL,
 true, false),

-- ── Deka Fit ──────────────────────────────────────────────────────────────────
('DEKA FIT Melbourne Shepparton',
 'deka-fit-melbourne-shepparton',
 'Deka Fit', 'race', 'Shepparton', 'Australia',
 '2026-08-01', '2026-08-02',
 'https://au.spartan.com/en/deka',
 NULL,
 true, true),

('DEKA Bangkok',
 'deka-bangkok',
 'Deka Fit', 'race', 'Bangkok', 'Thailand',
 '2026-10-31', '2026-11-01',
 'https://th.spartan.com',
 'Venue: Paragon Hall',
 true, false)

ON CONFLICT (slug) DO UPDATE SET
  title        = EXCLUDED.title,
  discipline   = EXCLUDED.discipline,
  event_type   = EXCLUDED.event_type,
  city         = EXCLUDED.city,
  country      = EXCLUDED.country,
  start_date   = EXCLUDED.start_date,
  end_date     = EXCLUDED.end_date,
  website_url  = EXCLUDED.website_url,
  description  = EXCLUDED.description,
  is_published = EXCLUDED.is_published,
  is_featured  = EXCLUDED.is_featured,
  updated_at   = now();

-- Verify
SELECT COUNT(*) AS total_rows FROM events;
SELECT COUNT(*) AS published_rows FROM events WHERE is_published = true;
SELECT title, start_date, country
  FROM events
  WHERE is_published = true
    AND start_date < '2099-01-01'
  ORDER BY start_date
  LIMIT 10;
